# Name of website and author
title: IRCbot
description: IRCbot is a community-developed, free and open source library for recording irc messages in Python 3.
author: Puneet Gopinath

safe: true

# Google Analytics id
google_analytics: UA-177058685-1

#include: [.htaccess]
#theme: jekyll-theme-modernist

encoding: "utf-8"
layouts_dir: _layouts
includes_dir: _includes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
